language: csharp
mono: none
solution: Bittrex.Net.sln
dotnet: 2.0.0
dist: trusty
script:
 - dotnet build Bittrex.Net/Bittrex.Net.csproj --framework "netstandard2.0"
 - dotnet test Bittrex.Net.UnitTests/Bittrex.Net.UnitTests.csproj